language: node_js
node_js:
  - '6'
cache: pip
install:
  - pip install awscli
script:
  - npm install
  - npm run build-production
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  skip_cleanup: true
  local_dir: build
  cache_control: "max-age=21600"
  acl: public_read
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
